services:
  - type: web
    name: Resume-builder
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn resume_builder.wsgi --bind=0.0.0.0:$PORT
    region: singapore
    preDeployCommand: | 
      python manage.py migrate
      python manage.py collectstatic --noinput
    envVars:
      - key: SECRET_KEY
        value: w%+kz=9e=28pb3#=0z&l)q3q6g9oz&53ujj58zx09cvh9wjhqn  # ✅ secure example
      - key: DEBUG
        value: False
      - key: RECAPTCHA_PUBLIC_KEY
        value: 6Ldp2T0rAAAAAHX3vMCQT9PKudfmLik6qonViCaR
      - key: RECAPTCHA_PRIVATE_KEY
        value: 6Ldp2T0rAAAAAD7lVQlrfaPIO025e3ZjeOBCXfi5
