# Generated by Django 5.2 on 2025-05-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='field_of_study',
        ),
        migrations.AddField(
            model_name='education',
            name='branch',
            field=models.CharField(blank=True, choices=[('SCIENCE', 'Science'), ('COMMERCE', 'Commerce'), ('ARTS', 'Arts'), ('CS', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication'), ('EEE', 'Electrical & Electronics'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('CHEM', 'Chemical Engineering'), ('AERO', 'Aeronautical Engineering'), ('AUTO', 'Automobile Engineering'), ('COMP_APP', 'Computer Applications'), ('SOFT_DEV', 'Software Development'), ('DATA_SCI', 'Data Science'), ('AI', 'Artificial Intelligence'), ('CYBER', 'Cyber Security'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('MATHS', 'Mathematics'), ('STATS', 'Statistics'), ('BIOTECH', 'Biotechnology'), ('ACCOUNT', 'Accountancy'), ('FINANCE', 'Finance'), ('MARKETING', 'Marketing'), ('HR', 'Human Resources'), ('ECO', 'Economics'), ('ENGLISH', 'English'), ('HISTORY', 'History'), ('PSYCH', 'Psychology'), ('SOCIO', 'Sociology')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='subjects',
            field=models.TextField(blank=True, help_text='Comma rated list of major subjects'),
        ),
        migrations.AddField(
            model_name='resume',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('HIGH_SCHOOL', 'High School'), ('SSC', 'Secondary School Certificate'), ('HSC', 'Higher Secondary Certificate'), ('DIPLOMA', 'Diploma'), ('BTECH', 'Bachelor of Technology'), ('BE', 'Bachelor of Engineering'), ('BSC', 'Bachelor of Science'), ('BCOM', 'Bachelor of Commerce'), ('BA', 'Bachelor of Arts'), ('BBA', 'Bachelor of Business Administration'), ('BCA', 'Bachelor of Computer Applications'), ('BARCH', 'Bachelor of Architecture'), ('LLB', 'Bachelor of Laws'), ('MTECH', 'Master of Technology'), ('ME', 'Master of Engineering'), ('MSC', 'Master of Science'), ('MCOM', 'Master of Commerce'), ('MA', 'Master of Arts'), ('MBA', 'Master of Business Administration'), ('MCA', 'Master of Computer Applications'), ('MARCH', 'Master of Architecture'), ('LLM', 'Master of Laws'), ('PHD', 'Doctor of Philosophy')], max_length=100),
        ),
    ]
