# Generated by Django 5.2 on 2025-05-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_education_field_of_study_education_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
