# Generated by Django 5.2 on 2025-05-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_resume_created_at_alter_resume_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('creative', 'Creative')], default='classic', max_length=20),
        ),
    ]
