# Generated by Django 5.2 on 2025-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('creative', 'Creative'), ('professional', 'Professional'), ('ats', 'ATS-Friendly')], default='classic', max_length=20),
        ),
    ]
