# Generated by Django 5.2 on 2025-05-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_skilllibrary_alter_skill_level_alter_skill_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillLibrary',
        ),
    ]
