# Generated by Django 5.2 on 2025-07-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_alter_resume_options_resume_job_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-popularity', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, to='resumes.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('programming', 'Programming'), ('framework', 'Framework'), ('tool', 'Tool'), ('language', 'Language'), ('soft', 'Soft Skill')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
    ]
