# Generated by Django 5.2 on 2025-07-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_alter_skill_options_alter_skill_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('programming', 'Programming Languages'), ('framework', 'Frameworks & Libraries'), ('frontend', 'Frontend Technologies'), ('backend', 'Backend Technologies'), ('database', 'Databases'), ('devops', 'DevOps & Cloud'), ('mobile', 'Mobile Development'), ('testing', 'Testing'), ('tools', 'Development Tools')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Intermediate', max_length=50),
        ),
    ]
