# Generated by Django 5.2 on 2025-07-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_alter_skill_options_alter_skill_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('creative', 'Creative'), ('professional', 'Professional'), ('ats', 'ATS-Friendly'), ('elegant', 'Elegant')], default='classic', max_length=20),
        ),
    ]
