# Generated by Django 5.2 on 2025-07-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_alter_resume_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
