# Generated by Django 5.2 on 2025-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0013_remove_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(help_text='e.g., Backend Developer, Frontend Engineer', max_length=100, verbose_name='Job Title'),
        ),
    ]
