# Generated by Django 5.2 on 2025-07-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0014_alter_resume_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_title',
        ),
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_country_code',
            field=models.CharField(default='+1', max_length=7),
        ),
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
